table 'hospital_locations csv'
	lineageTag: 04227863-6a43-487f-97ac-2d6f7f272d90

	column Location_ID
		dataType: string
		lineageTag: b4c60b92-b5bf-4971-bc22-6f882ca5de54
		summarizeBy: none
		sourceColumn: Location_ID

		annotation SummarizationSetBy = Automatic

	column Location_Name
		dataType: string
		lineageTag: b477d85b-e051-4cb7-b797-79935b50a43e
		summarizeBy: none
		sourceColumn: Location_Name

		annotation SummarizationSetBy = Automatic

	column Facility_Type
		dataType: string
		lineageTag: 3f96c91e-7dd7-438d-bef5-0994482468aa
		summarizeBy: none
		sourceColumn: Facility_Type

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 0575f23a-ec9d-45ef-b837-1ee3e9ea6a43
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 41d4b05c-ad5e-4cbf-920e-34d33cb917ec
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 33e654d5-5a29-4eb7-896c-be9b407a8fbf
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a9478b10-43cf-4f39-ac63-c2b7f2067553
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 7b761559-b5bb-468d-bb42-bf69e5172a15
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 42e232e0-ff2a-4772-9e85-8eaea8ee4fe0
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'hospital_locations csv' = m
		mode: import
		source =
				let
				    Source = Folder.Files(Source),
				    #"E:\Addend Analytics\Health Github\Samplte Data 2\_hospital_locations csv1" = Source{[#"Folder Path"=Source2,Name="hospital_locations.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"E:\Addend Analytics\Health Github\Samplte Data 2\_hospital_locations csv1",[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Location_ID", type text}, {"Location_Name", type text}, {"Facility_Type", type text}, {"Address", type text}, {"City", type text}, {"Region", type text}, {"Country", type text}, {"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

